export { default as PatientsSVG } from "./PatientsSVG"
export { default as ConsultaionsSVG } from "./ConsultaionsSVG"
export { default as EmergencyRoomSVG } from "./EmergencyRoomSVG"
export { default as AuthSVG } from "./AuthSVG"
export { default as OtpSVG } from "./OtpSVG"
export { default as FingerPrint } from "./FingerPrint"
export { default as FlagSVG } from "./FlagSVG"
