export { default as PatientsSVG } from "./PatientsSVG"
export { default as ConsultaionsSVG } from "./ConsultaionsSVG"
export { default as EmergencyRoomSVG } from "./EmergencyRoomSVG"
export { default as ClearSVG } from "./ClearSVG"
export { default as PasswordEyeSVG } from "./PasswordEyeSVG"
