export { default as AuthSVG } from "./AuthSVG"
export { default as OtpSVG } from "./OtpSVG"
export { default as FingerPrint } from "./FingerPrint"
export { default as FlagSVG } from "./FlagSVG"
export { default as HomeSVG } from "./HomeSVG"
export { default as NotificationSVG } from "./NotificationSVG"
export { default as PatientSVG } from "./PatientSVG"
export { default as ConsultationSVG } from "./ConsultationSVG"
